
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x500")
window.configure(bg = "#FFFFFF")

#-------------------------------- Save image --------------------------------#
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))



canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 500,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)

# BUTTON "BACK"
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=19.00000000000003,
    y=13.0,
    width=85.0,
    height=34.0
)

# BUTTON "SUBMIT"
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=292.0,
    y=395.0,
    width=216.0,
    height=50.0
)

# ENTRY USERNAME
entry_bg_1 = canvas.create_image(
    400.0,
    336.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_1.place(
    x=258.0,
    y=311.0 + 8,
    width=284.0,
    height=36.0
)


# ENTRY PASSWORD
entry_bg_2 = canvas.create_image(
    400.0,
    242.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_2.place(
    x=258.0,
    y=217.0 + 8,
    width=284.0,
    height=36.0
)


# ENTRY BANK ACCOUNT
entry_bg_3 = canvas.create_image(
    400.0,
    148.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_3.place(
    x=258.0,
    y=123.0 + 8,
    width=284.0,
    height=36.0
)

canvas.create_text(
    250.00000000000003,
    290.0,
    anchor="nw",
    text="Bank account (10 characters, 0-9)",
    fill="#000000",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    250.00000000000003,
    195.0,
    anchor="nw",
    text="password",
    fill="#000000",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    250.00000000000003,
    102.0,
    anchor="nw",
    text="username",
    fill="#000000",
    font=("Roboto Bold", 16 * -1)
)

canvas.create_text(
    330.0,
    39.0,
    anchor="nw",
    text="Sign up",
    fill="#000000",
    font=("Roboto Bold", 36 * -1)
)
window.resizable(False, False)
window.mainloop()
