
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x500")
window.configure(bg = "#FFFFFF")


#---------------------------- Implement Function ----------------------------#
def clearScreen(self = window):
    for widget in self.place_slaves():
        widget.place_forget()



#---------------------------- Tkinter Designer -----------------------------#
canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 500,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    1.1368683772161603e-13,
    5.684341886080802e-14,
    400.0000000000001,
    500.00000000000006,
    fill="#F2425F",
    outline="")

canvas.create_rectangle(
    139.9999999999999,
    329.99999999999994,
    259.9999999999999,
    440.99999999999994,
    fill="#F2425F",
    outline="")

canvas.create_text(
    439.9999999999999,
    448.99999999999994,
    anchor="nw",
    text="If you dont have an account,",
    fill="#000000",
    font=("Roboto Bold", 18 * -1)
)

canvas.create_rectangle(
    469.9999999999999,
    416.99999999999994,
    729.9999999999999,
    418.99999999999994,
    fill="#F2425F",
    outline="")

canvas.create_text(
    454.9999999999999,
    208.99999999999994,
    anchor="nw",
    text="password",
    fill="#000000",
    font=("Roboto Bold", 20 * -1)
)

canvas.create_text(
    454.9999999999999,
    116.99999999999994,
    anchor="nw",
    text="username",
    fill="#000000",
    font=("Roboto Bold", 20 * -1)
)

canvas.create_text(
    454.9999999999999,
    49.99999999999994,
    anchor="nw",
    text="Log in",
    fill="#000000",
    font=("Roboto Bold", 36 * -1)
)

canvas.create_text(
    32.999999999999886,
    90.99999999999994,
    anchor="nw",
    text="Welcome to Go2Chill",
    fill="#FFFFFF",
    font=("Roboto Bold", 28 * -1)
)

canvas.create_rectangle(
    32.999999999999886,
    150.99999999999994,
    192.9999999999999,
    152.99999999999994,
    fill="#FFFFFF",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=665.9999999999999,
    y=442.99999999999994,
    width=96.0,
    height=34.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=clearScreen,
    relief="flat"
)
button_2.place(
    x=449.9999999999999,
    y=329.99999999999994,
    width=300.0,
    height=50.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    599.9999999999999,
    261.99999999999994,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_1.place(
    x=457.9999999999999,
    y=244,
    width=284.0,
    height=36.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    599.9999999999999,
    167.99999999999994,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_2.place(
    x=457.9999999999999,
    y=150,
    width=284.0,
    height=36.0
)

canvas.create_text(
    32.999999999999886,
    192.99999999999994,
    anchor="nw",
    text="The application provides easy and",
    fill="#FFFFFF",
    font=("Roboto Bold", 18 * -1)
)

canvas.create_text(
    32.999999999999886,
    213.99999999999994,
    anchor="nw",
    text="convenient booking service for you.",
    fill="#FFFFFF",
    font=("Roboto Bold", 18 * -1)
)

canvas.create_text(
    32.999999999999886,
    247.99999999999994,
    anchor="nw",
    text="Bringing you the feeling of always having",
    fill="#FFFFFF",
    font=("Roboto Bold", 18 * -1)
)

canvas.create_text(
    32.999999999999886,
    268.99999999999994,
    anchor="nw",
    text="moments of relaxation and comfort.",
    fill="#FFFFFF",
    font=("Roboto Bold", 18 * -1)
)
window.resizable(False, False)
window.mainloop()
